/*
Kalshi API.

This documentation describes Kalshi's REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kalshiAPI

import (
	"encoding/json"
)

// GetNotificationPreferencesResponse struct for GetNotificationPreferencesResponse
type GetNotificationPreferencesResponse struct {
	Preferences SubscriptionPreference `json:"preferences"`
}

// NewGetNotificationPreferencesResponse instantiates a new GetNotificationPreferencesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNotificationPreferencesResponse(preferences SubscriptionPreference) *GetNotificationPreferencesResponse {
	this := GetNotificationPreferencesResponse{}
	this.Preferences = preferences
	return &this
}

// NewGetNotificationPreferencesResponseWithDefaults instantiates a new GetNotificationPreferencesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNotificationPreferencesResponseWithDefaults() *GetNotificationPreferencesResponse {
	this := GetNotificationPreferencesResponse{}
	return &this
}

// GetPreferences returns the Preferences field value
func (o *GetNotificationPreferencesResponse) GetPreferences() SubscriptionPreference {
	if o == nil {
		var ret SubscriptionPreference
		return ret
	}

	return o.Preferences
}

// GetPreferencesOk returns a tuple with the Preferences field value
// and a boolean to check if the value has been set.
func (o *GetNotificationPreferencesResponse) GetPreferencesOk() (*SubscriptionPreference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Preferences, true
}

// SetPreferences sets field value
func (o *GetNotificationPreferencesResponse) SetPreferences(v SubscriptionPreference) {
	o.Preferences = v
}

func (o GetNotificationPreferencesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["preferences"] = o.Preferences
	}
	return json.Marshal(toSerialize)
}

type NullableGetNotificationPreferencesResponse struct {
	value *GetNotificationPreferencesResponse
	isSet bool
}

func (v NullableGetNotificationPreferencesResponse) Get() *GetNotificationPreferencesResponse {
	return v.value
}

func (v *NullableGetNotificationPreferencesResponse) Set(val *GetNotificationPreferencesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNotificationPreferencesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNotificationPreferencesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNotificationPreferencesResponse(val *GetNotificationPreferencesResponse) *NullableGetNotificationPreferencesResponse {
	return &NullableGetNotificationPreferencesResponse{value: val, isSet: true}
}

func (v NullableGetNotificationPreferencesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNotificationPreferencesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


