/*
Kalshi API.

This documentation describes Kalshi's REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kalshiAPI

import (
	"encoding/json"
)

// UserWithdrawalRequest struct for UserWithdrawalRequest
type UserWithdrawalRequest struct {
	AmountCents int64 `json:"amount_cents"`
	BankId string `json:"bank_id"`
	FeeCents int64 `json:"fee_cents"`
}

// NewUserWithdrawalRequest instantiates a new UserWithdrawalRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserWithdrawalRequest(amountCents int64, bankId string, feeCents int64) *UserWithdrawalRequest {
	this := UserWithdrawalRequest{}
	this.AmountCents = amountCents
	this.BankId = bankId
	this.FeeCents = feeCents
	return &this
}

// NewUserWithdrawalRequestWithDefaults instantiates a new UserWithdrawalRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserWithdrawalRequestWithDefaults() *UserWithdrawalRequest {
	this := UserWithdrawalRequest{}
	return &this
}

// GetAmountCents returns the AmountCents field value
func (o *UserWithdrawalRequest) GetAmountCents() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.AmountCents
}

// GetAmountCentsOk returns a tuple with the AmountCents field value
// and a boolean to check if the value has been set.
func (o *UserWithdrawalRequest) GetAmountCentsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmountCents, true
}

// SetAmountCents sets field value
func (o *UserWithdrawalRequest) SetAmountCents(v int64) {
	o.AmountCents = v
}

// GetBankId returns the BankId field value
func (o *UserWithdrawalRequest) GetBankId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankId
}

// GetBankIdOk returns a tuple with the BankId field value
// and a boolean to check if the value has been set.
func (o *UserWithdrawalRequest) GetBankIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankId, true
}

// SetBankId sets field value
func (o *UserWithdrawalRequest) SetBankId(v string) {
	o.BankId = v
}

// GetFeeCents returns the FeeCents field value
func (o *UserWithdrawalRequest) GetFeeCents() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FeeCents
}

// GetFeeCentsOk returns a tuple with the FeeCents field value
// and a boolean to check if the value has been set.
func (o *UserWithdrawalRequest) GetFeeCentsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeeCents, true
}

// SetFeeCents sets field value
func (o *UserWithdrawalRequest) SetFeeCents(v int64) {
	o.FeeCents = v
}

func (o UserWithdrawalRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["amount_cents"] = o.AmountCents
	}
	if true {
		toSerialize["bank_id"] = o.BankId
	}
	if true {
		toSerialize["fee_cents"] = o.FeeCents
	}
	return json.Marshal(toSerialize)
}

type NullableUserWithdrawalRequest struct {
	value *UserWithdrawalRequest
	isSet bool
}

func (v NullableUserWithdrawalRequest) Get() *UserWithdrawalRequest {
	return v.value
}

func (v *NullableUserWithdrawalRequest) Set(val *UserWithdrawalRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserWithdrawalRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserWithdrawalRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserWithdrawalRequest(val *UserWithdrawalRequest) *NullableUserWithdrawalRequest {
	return &NullableUserWithdrawalRequest{value: val, isSet: true}
}

func (v NullableUserWithdrawalRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserWithdrawalRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


