/*
Kalshi API.

This documentation describes Kalshi's REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kalshiAPI

import (
	"encoding/json"
)

// GetRangedMarketsResponse struct for GetRangedMarketsResponse
type GetRangedMarketsResponse struct {
	RangedMarkets []RangedMarket `json:"ranged_markets"`
}

// NewGetRangedMarketsResponse instantiates a new GetRangedMarketsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRangedMarketsResponse(rangedMarkets []RangedMarket) *GetRangedMarketsResponse {
	this := GetRangedMarketsResponse{}
	this.RangedMarkets = rangedMarkets
	return &this
}

// NewGetRangedMarketsResponseWithDefaults instantiates a new GetRangedMarketsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRangedMarketsResponseWithDefaults() *GetRangedMarketsResponse {
	this := GetRangedMarketsResponse{}
	return &this
}

// GetRangedMarkets returns the RangedMarkets field value
func (o *GetRangedMarketsResponse) GetRangedMarkets() []RangedMarket {
	if o == nil {
		var ret []RangedMarket
		return ret
	}

	return o.RangedMarkets
}

// GetRangedMarketsOk returns a tuple with the RangedMarkets field value
// and a boolean to check if the value has been set.
func (o *GetRangedMarketsResponse) GetRangedMarketsOk() ([]RangedMarket, bool) {
	if o == nil {
		return nil, false
	}
	return o.RangedMarkets, true
}

// SetRangedMarkets sets field value
func (o *GetRangedMarketsResponse) SetRangedMarkets(v []RangedMarket) {
	o.RangedMarkets = v
}

func (o GetRangedMarketsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ranged_markets"] = o.RangedMarkets
	}
	return json.Marshal(toSerialize)
}

type NullableGetRangedMarketsResponse struct {
	value *GetRangedMarketsResponse
	isSet bool
}

func (v NullableGetRangedMarketsResponse) Get() *GetRangedMarketsResponse {
	return v.value
}

func (v *NullableGetRangedMarketsResponse) Set(val *GetRangedMarketsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRangedMarketsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRangedMarketsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRangedMarketsResponse(val *GetRangedMarketsResponse) *NullableGetRangedMarketsResponse {
	return &NullableGetRangedMarketsResponse{value: val, isSet: true}
}

func (v NullableGetRangedMarketsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRangedMarketsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


