/*
Kalshi API.

This documentation describes Kalshi's REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kalshiAPI

import (
	"encoding/json"
)

// GetCandlestickMarketHistoryResponse struct for GetCandlestickMarketHistoryResponse
type GetCandlestickMarketHistoryResponse struct {
	Points []MarketHistoryCandleStickInfo `json:"points"`
}

// NewGetCandlestickMarketHistoryResponse instantiates a new GetCandlestickMarketHistoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCandlestickMarketHistoryResponse(points []MarketHistoryCandleStickInfo) *GetCandlestickMarketHistoryResponse {
	this := GetCandlestickMarketHistoryResponse{}
	this.Points = points
	return &this
}

// NewGetCandlestickMarketHistoryResponseWithDefaults instantiates a new GetCandlestickMarketHistoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCandlestickMarketHistoryResponseWithDefaults() *GetCandlestickMarketHistoryResponse {
	this := GetCandlestickMarketHistoryResponse{}
	return &this
}

// GetPoints returns the Points field value
func (o *GetCandlestickMarketHistoryResponse) GetPoints() []MarketHistoryCandleStickInfo {
	if o == nil {
		var ret []MarketHistoryCandleStickInfo
		return ret
	}

	return o.Points
}

// GetPointsOk returns a tuple with the Points field value
// and a boolean to check if the value has been set.
func (o *GetCandlestickMarketHistoryResponse) GetPointsOk() ([]MarketHistoryCandleStickInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Points, true
}

// SetPoints sets field value
func (o *GetCandlestickMarketHistoryResponse) SetPoints(v []MarketHistoryCandleStickInfo) {
	o.Points = v
}

func (o GetCandlestickMarketHistoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["points"] = o.Points
	}
	return json.Marshal(toSerialize)
}

type NullableGetCandlestickMarketHistoryResponse struct {
	value *GetCandlestickMarketHistoryResponse
	isSet bool
}

func (v NullableGetCandlestickMarketHistoryResponse) Get() *GetCandlestickMarketHistoryResponse {
	return v.value
}

func (v *NullableGetCandlestickMarketHistoryResponse) Set(val *GetCandlestickMarketHistoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCandlestickMarketHistoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCandlestickMarketHistoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCandlestickMarketHistoryResponse(val *GetCandlestickMarketHistoryResponse) *NullableGetCandlestickMarketHistoryResponse {
	return &NullableGetCandlestickMarketHistoryResponse{value: val, isSet: true}
}

func (v NullableGetCandlestickMarketHistoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCandlestickMarketHistoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


