/*
Kalshi API.

This documentation describes Kalshi's REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kalshiAPI

import (
	"encoding/json"
)

// UserOrderDecreaseResponse struct for UserOrderDecreaseResponse
type UserOrderDecreaseResponse struct {
	Order Order `json:"order"`
	// Result of the decrease operation
	ReducedBy int32 `json:"reduced_by"`
}

// NewUserOrderDecreaseResponse instantiates a new UserOrderDecreaseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserOrderDecreaseResponse(order Order, reducedBy int32) *UserOrderDecreaseResponse {
	this := UserOrderDecreaseResponse{}
	this.Order = order
	this.ReducedBy = reducedBy
	return &this
}

// NewUserOrderDecreaseResponseWithDefaults instantiates a new UserOrderDecreaseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserOrderDecreaseResponseWithDefaults() *UserOrderDecreaseResponse {
	this := UserOrderDecreaseResponse{}
	return &this
}

// GetOrder returns the Order field value
func (o *UserOrderDecreaseResponse) GetOrder() Order {
	if o == nil {
		var ret Order
		return ret
	}

	return o.Order
}

// GetOrderOk returns a tuple with the Order field value
// and a boolean to check if the value has been set.
func (o *UserOrderDecreaseResponse) GetOrderOk() (*Order, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Order, true
}

// SetOrder sets field value
func (o *UserOrderDecreaseResponse) SetOrder(v Order) {
	o.Order = v
}

// GetReducedBy returns the ReducedBy field value
func (o *UserOrderDecreaseResponse) GetReducedBy() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReducedBy
}

// GetReducedByOk returns a tuple with the ReducedBy field value
// and a boolean to check if the value has been set.
func (o *UserOrderDecreaseResponse) GetReducedByOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReducedBy, true
}

// SetReducedBy sets field value
func (o *UserOrderDecreaseResponse) SetReducedBy(v int32) {
	o.ReducedBy = v
}

func (o UserOrderDecreaseResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["order"] = o.Order
	}
	if true {
		toSerialize["reduced_by"] = o.ReducedBy
	}
	return json.Marshal(toSerialize)
}

type NullableUserOrderDecreaseResponse struct {
	value *UserOrderDecreaseResponse
	isSet bool
}

func (v NullableUserOrderDecreaseResponse) Get() *UserOrderDecreaseResponse {
	return v.value
}

func (v *NullableUserOrderDecreaseResponse) Set(val *UserOrderDecreaseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserOrderDecreaseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserOrderDecreaseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserOrderDecreaseResponse(val *UserOrderDecreaseResponse) *NullableUserOrderDecreaseResponse {
	return &NullableUserOrderDecreaseResponse{value: val, isSet: true}
}

func (v NullableUserOrderDecreaseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserOrderDecreaseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


