/*
Kalshi API.

This documentation describes Kalshi's REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kalshiAPI

import (
	"encoding/json"
)

// UserGetCurrentPortfolioValueResponse struct for UserGetCurrentPortfolioValueResponse
type UserGetCurrentPortfolioValueResponse struct {
	Value *PortfolioMeasurement `json:"value,omitempty"`
}

// NewUserGetCurrentPortfolioValueResponse instantiates a new UserGetCurrentPortfolioValueResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserGetCurrentPortfolioValueResponse() *UserGetCurrentPortfolioValueResponse {
	this := UserGetCurrentPortfolioValueResponse{}
	return &this
}

// NewUserGetCurrentPortfolioValueResponseWithDefaults instantiates a new UserGetCurrentPortfolioValueResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserGetCurrentPortfolioValueResponseWithDefaults() *UserGetCurrentPortfolioValueResponse {
	this := UserGetCurrentPortfolioValueResponse{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *UserGetCurrentPortfolioValueResponse) GetValue() PortfolioMeasurement {
	if o == nil || o.Value == nil {
		var ret PortfolioMeasurement
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGetCurrentPortfolioValueResponse) GetValueOk() (*PortfolioMeasurement, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *UserGetCurrentPortfolioValueResponse) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given PortfolioMeasurement and assigns it to the Value field.
func (o *UserGetCurrentPortfolioValueResponse) SetValue(v PortfolioMeasurement) {
	o.Value = &v
}

func (o UserGetCurrentPortfolioValueResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableUserGetCurrentPortfolioValueResponse struct {
	value *UserGetCurrentPortfolioValueResponse
	isSet bool
}

func (v NullableUserGetCurrentPortfolioValueResponse) Get() *UserGetCurrentPortfolioValueResponse {
	return v.value
}

func (v *NullableUserGetCurrentPortfolioValueResponse) Set(val *UserGetCurrentPortfolioValueResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserGetCurrentPortfolioValueResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserGetCurrentPortfolioValueResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserGetCurrentPortfolioValueResponse(val *UserGetCurrentPortfolioValueResponse) *NullableUserGetCurrentPortfolioValueResponse {
	return &NullableUserGetCurrentPortfolioValueResponse{value: val, isSet: true}
}

func (v NullableUserGetCurrentPortfolioValueResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserGetCurrentPortfolioValueResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


