/*
Kalshi API.

This documentation describes Kalshi's REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kalshiAPI

import (
	"encoding/json"
)

// UserGetMarketPositionsResponse struct for UserGetMarketPositionsResponse
type UserGetMarketPositionsResponse struct {
	// List of market positions
	MarketPositions []MarketPosition `json:"market_positions"`
}

// NewUserGetMarketPositionsResponse instantiates a new UserGetMarketPositionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserGetMarketPositionsResponse(marketPositions []MarketPosition) *UserGetMarketPositionsResponse {
	this := UserGetMarketPositionsResponse{}
	this.MarketPositions = marketPositions
	return &this
}

// NewUserGetMarketPositionsResponseWithDefaults instantiates a new UserGetMarketPositionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserGetMarketPositionsResponseWithDefaults() *UserGetMarketPositionsResponse {
	this := UserGetMarketPositionsResponse{}
	return &this
}

// GetMarketPositions returns the MarketPositions field value
func (o *UserGetMarketPositionsResponse) GetMarketPositions() []MarketPosition {
	if o == nil {
		var ret []MarketPosition
		return ret
	}

	return o.MarketPositions
}

// GetMarketPositionsOk returns a tuple with the MarketPositions field value
// and a boolean to check if the value has been set.
func (o *UserGetMarketPositionsResponse) GetMarketPositionsOk() ([]MarketPosition, bool) {
	if o == nil {
		return nil, false
	}
	return o.MarketPositions, true
}

// SetMarketPositions sets field value
func (o *UserGetMarketPositionsResponse) SetMarketPositions(v []MarketPosition) {
	o.MarketPositions = v
}

func (o UserGetMarketPositionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["market_positions"] = o.MarketPositions
	}
	return json.Marshal(toSerialize)
}

type NullableUserGetMarketPositionsResponse struct {
	value *UserGetMarketPositionsResponse
	isSet bool
}

func (v NullableUserGetMarketPositionsResponse) Get() *UserGetMarketPositionsResponse {
	return v.value
}

func (v *NullableUserGetMarketPositionsResponse) Set(val *UserGetMarketPositionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserGetMarketPositionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserGetMarketPositionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserGetMarketPositionsResponse(val *UserGetMarketPositionsResponse) *NullableUserGetMarketPositionsResponse {
	return &NullableUserGetMarketPositionsResponse{value: val, isSet: true}
}

func (v NullableUserGetMarketPositionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserGetMarketPositionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


