/*
Kalshi API.

This documentation describes Kalshi's REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kalshiAPI

import (
	"encoding/json"
)

// GetRangedMarketResponse struct for GetRangedMarketResponse
type GetRangedMarketResponse struct {
	RangedMarket RangedMarket `json:"ranged_market"`
}

// NewGetRangedMarketResponse instantiates a new GetRangedMarketResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRangedMarketResponse(rangedMarket RangedMarket) *GetRangedMarketResponse {
	this := GetRangedMarketResponse{}
	this.RangedMarket = rangedMarket
	return &this
}

// NewGetRangedMarketResponseWithDefaults instantiates a new GetRangedMarketResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRangedMarketResponseWithDefaults() *GetRangedMarketResponse {
	this := GetRangedMarketResponse{}
	return &this
}

// GetRangedMarket returns the RangedMarket field value
func (o *GetRangedMarketResponse) GetRangedMarket() RangedMarket {
	if o == nil {
		var ret RangedMarket
		return ret
	}

	return o.RangedMarket
}

// GetRangedMarketOk returns a tuple with the RangedMarket field value
// and a boolean to check if the value has been set.
func (o *GetRangedMarketResponse) GetRangedMarketOk() (*RangedMarket, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RangedMarket, true
}

// SetRangedMarket sets field value
func (o *GetRangedMarketResponse) SetRangedMarket(v RangedMarket) {
	o.RangedMarket = v
}

func (o GetRangedMarketResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ranged_market"] = o.RangedMarket
	}
	return json.Marshal(toSerialize)
}

type NullableGetRangedMarketResponse struct {
	value *GetRangedMarketResponse
	isSet bool
}

func (v NullableGetRangedMarketResponse) Get() *GetRangedMarketResponse {
	return v.value
}

func (v *NullableGetRangedMarketResponse) Set(val *GetRangedMarketResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRangedMarketResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRangedMarketResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRangedMarketResponse(val *GetRangedMarketResponse) *NullableGetRangedMarketResponse {
	return &NullableGetRangedMarketResponse{value: val, isSet: true}
}

func (v NullableGetRangedMarketResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRangedMarketResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


