/*
Kalshi API.

This documentation describes Kalshi's REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kalshiAPI

import (
	"encoding/json"
)

// GetMarketHistoryResponse struct for GetMarketHistoryResponse
type GetMarketHistoryResponse struct {
	MarketStatsPoints []MarketStatsPoint `json:"market_stats_points"`
}

// NewGetMarketHistoryResponse instantiates a new GetMarketHistoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMarketHistoryResponse(marketStatsPoints []MarketStatsPoint) *GetMarketHistoryResponse {
	this := GetMarketHistoryResponse{}
	this.MarketStatsPoints = marketStatsPoints
	return &this
}

// NewGetMarketHistoryResponseWithDefaults instantiates a new GetMarketHistoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMarketHistoryResponseWithDefaults() *GetMarketHistoryResponse {
	this := GetMarketHistoryResponse{}
	return &this
}

// GetMarketStatsPoints returns the MarketStatsPoints field value
func (o *GetMarketHistoryResponse) GetMarketStatsPoints() []MarketStatsPoint {
	if o == nil {
		var ret []MarketStatsPoint
		return ret
	}

	return o.MarketStatsPoints
}

// GetMarketStatsPointsOk returns a tuple with the MarketStatsPoints field value
// and a boolean to check if the value has been set.
func (o *GetMarketHistoryResponse) GetMarketStatsPointsOk() ([]MarketStatsPoint, bool) {
	if o == nil {
		return nil, false
	}
	return o.MarketStatsPoints, true
}

// SetMarketStatsPoints sets field value
func (o *GetMarketHistoryResponse) SetMarketStatsPoints(v []MarketStatsPoint) {
	o.MarketStatsPoints = v
}

func (o GetMarketHistoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["market_stats_points"] = o.MarketStatsPoints
	}
	return json.Marshal(toSerialize)
}

type NullableGetMarketHistoryResponse struct {
	value *GetMarketHistoryResponse
	isSet bool
}

func (v NullableGetMarketHistoryResponse) Get() *GetMarketHistoryResponse {
	return v.value
}

func (v *NullableGetMarketHistoryResponse) Set(val *GetMarketHistoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMarketHistoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMarketHistoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMarketHistoryResponse(val *GetMarketHistoryResponse) *NullableGetMarketHistoryResponse {
	return &NullableGetMarketHistoryResponse{value: val, isSet: true}
}

func (v NullableGetMarketHistoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMarketHistoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


