/*
Kalshi API.

This documentation describes Kalshi's REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kalshiAPI

import (
	"encoding/json"
)

// GetUserImmediateFundingResponse struct for GetUserImmediateFundingResponse
type GetUserImmediateFundingResponse struct {
	DepositFeeCents int64 `json:"deposit_fee_cents"`
	ImmediateAmountBeingUsed int64 `json:"immediate_amount_being_used"`
	ImmediateAmountRemaining int64 `json:"immediate_amount_remaining"`
	ImmediateDepositAmount int64 `json:"immediate_deposit_amount"`
}

// NewGetUserImmediateFundingResponse instantiates a new GetUserImmediateFundingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserImmediateFundingResponse(depositFeeCents int64, immediateAmountBeingUsed int64, immediateAmountRemaining int64, immediateDepositAmount int64) *GetUserImmediateFundingResponse {
	this := GetUserImmediateFundingResponse{}
	this.DepositFeeCents = depositFeeCents
	this.ImmediateAmountBeingUsed = immediateAmountBeingUsed
	this.ImmediateAmountRemaining = immediateAmountRemaining
	this.ImmediateDepositAmount = immediateDepositAmount
	return &this
}

// NewGetUserImmediateFundingResponseWithDefaults instantiates a new GetUserImmediateFundingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserImmediateFundingResponseWithDefaults() *GetUserImmediateFundingResponse {
	this := GetUserImmediateFundingResponse{}
	return &this
}

// GetDepositFeeCents returns the DepositFeeCents field value
func (o *GetUserImmediateFundingResponse) GetDepositFeeCents() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DepositFeeCents
}

// GetDepositFeeCentsOk returns a tuple with the DepositFeeCents field value
// and a boolean to check if the value has been set.
func (o *GetUserImmediateFundingResponse) GetDepositFeeCentsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DepositFeeCents, true
}

// SetDepositFeeCents sets field value
func (o *GetUserImmediateFundingResponse) SetDepositFeeCents(v int64) {
	o.DepositFeeCents = v
}

// GetImmediateAmountBeingUsed returns the ImmediateAmountBeingUsed field value
func (o *GetUserImmediateFundingResponse) GetImmediateAmountBeingUsed() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ImmediateAmountBeingUsed
}

// GetImmediateAmountBeingUsedOk returns a tuple with the ImmediateAmountBeingUsed field value
// and a boolean to check if the value has been set.
func (o *GetUserImmediateFundingResponse) GetImmediateAmountBeingUsedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImmediateAmountBeingUsed, true
}

// SetImmediateAmountBeingUsed sets field value
func (o *GetUserImmediateFundingResponse) SetImmediateAmountBeingUsed(v int64) {
	o.ImmediateAmountBeingUsed = v
}

// GetImmediateAmountRemaining returns the ImmediateAmountRemaining field value
func (o *GetUserImmediateFundingResponse) GetImmediateAmountRemaining() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ImmediateAmountRemaining
}

// GetImmediateAmountRemainingOk returns a tuple with the ImmediateAmountRemaining field value
// and a boolean to check if the value has been set.
func (o *GetUserImmediateFundingResponse) GetImmediateAmountRemainingOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImmediateAmountRemaining, true
}

// SetImmediateAmountRemaining sets field value
func (o *GetUserImmediateFundingResponse) SetImmediateAmountRemaining(v int64) {
	o.ImmediateAmountRemaining = v
}

// GetImmediateDepositAmount returns the ImmediateDepositAmount field value
func (o *GetUserImmediateFundingResponse) GetImmediateDepositAmount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ImmediateDepositAmount
}

// GetImmediateDepositAmountOk returns a tuple with the ImmediateDepositAmount field value
// and a boolean to check if the value has been set.
func (o *GetUserImmediateFundingResponse) GetImmediateDepositAmountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImmediateDepositAmount, true
}

// SetImmediateDepositAmount sets field value
func (o *GetUserImmediateFundingResponse) SetImmediateDepositAmount(v int64) {
	o.ImmediateDepositAmount = v
}

func (o GetUserImmediateFundingResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["deposit_fee_cents"] = o.DepositFeeCents
	}
	if true {
		toSerialize["immediate_amount_being_used"] = o.ImmediateAmountBeingUsed
	}
	if true {
		toSerialize["immediate_amount_remaining"] = o.ImmediateAmountRemaining
	}
	if true {
		toSerialize["immediate_deposit_amount"] = o.ImmediateDepositAmount
	}
	return json.Marshal(toSerialize)
}

type NullableGetUserImmediateFundingResponse struct {
	value *GetUserImmediateFundingResponse
	isSet bool
}

func (v NullableGetUserImmediateFundingResponse) Get() *GetUserImmediateFundingResponse {
	return v.value
}

func (v *NullableGetUserImmediateFundingResponse) Set(val *GetUserImmediateFundingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserImmediateFundingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserImmediateFundingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserImmediateFundingResponse(val *GetUserImmediateFundingResponse) *NullableGetUserImmediateFundingResponse {
	return &NullableGetUserImmediateFundingResponse{value: val, isSet: true}
}

func (v NullableGetUserImmediateFundingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserImmediateFundingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


