/*
Kalshi API.

This documentation describes Kalshi's REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kalshiAPI

import (
	"encoding/json"
)

// DeprecatedPortfolioMeasurement Deprecated Portfolio measurement is simply a snapshot of the portfolio of a user on a timestamp.  This is going to get deprecated soon.
type DeprecatedPortfolioMeasurement struct {
	A int64 `json:"a"`
	BalanceChange *int64 `json:"balance_change,omitempty"`
	CumulativeDeposits int64 `json:"cumulative_deposits"`
	// Count of settlements member has had from account creation to timestamp (inclusive)
	CumulativeNumberSettlements int64 `json:"cumulative_number_settlements"`
	CumulativeWithdrawals int64 `json:"cumulative_withdrawals"`
	// Reasons for the portfolio value change, if applicable
	Reason *string `json:"reason,omitempty"`
	// Timestamp of the read in UNIX timestamp. (https://www.unixtimestamp.com/)
	Ts int64 `json:"ts"`
	V int64 `json:"v"`
}

// NewDeprecatedPortfolioMeasurement instantiates a new DeprecatedPortfolioMeasurement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeprecatedPortfolioMeasurement(a int64, cumulativeDeposits int64, cumulativeNumberSettlements int64, cumulativeWithdrawals int64, ts int64, v int64) *DeprecatedPortfolioMeasurement {
	this := DeprecatedPortfolioMeasurement{}
	this.A = a
	this.CumulativeDeposits = cumulativeDeposits
	this.CumulativeNumberSettlements = cumulativeNumberSettlements
	this.CumulativeWithdrawals = cumulativeWithdrawals
	this.Ts = ts
	this.V = v
	return &this
}

// NewDeprecatedPortfolioMeasurementWithDefaults instantiates a new DeprecatedPortfolioMeasurement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeprecatedPortfolioMeasurementWithDefaults() *DeprecatedPortfolioMeasurement {
	this := DeprecatedPortfolioMeasurement{}
	return &this
}

// GetA returns the A field value
func (o *DeprecatedPortfolioMeasurement) GetA() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.A
}

// GetAOk returns a tuple with the A field value
// and a boolean to check if the value has been set.
func (o *DeprecatedPortfolioMeasurement) GetAOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.A, true
}

// SetA sets field value
func (o *DeprecatedPortfolioMeasurement) SetA(v int64) {
	o.A = v
}

// GetBalanceChange returns the BalanceChange field value if set, zero value otherwise.
func (o *DeprecatedPortfolioMeasurement) GetBalanceChange() int64 {
	if o == nil || o.BalanceChange == nil {
		var ret int64
		return ret
	}
	return *o.BalanceChange
}

// GetBalanceChangeOk returns a tuple with the BalanceChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeprecatedPortfolioMeasurement) GetBalanceChangeOk() (*int64, bool) {
	if o == nil || o.BalanceChange == nil {
		return nil, false
	}
	return o.BalanceChange, true
}

// HasBalanceChange returns a boolean if a field has been set.
func (o *DeprecatedPortfolioMeasurement) HasBalanceChange() bool {
	if o != nil && o.BalanceChange != nil {
		return true
	}

	return false
}

// SetBalanceChange gets a reference to the given int64 and assigns it to the BalanceChange field.
func (o *DeprecatedPortfolioMeasurement) SetBalanceChange(v int64) {
	o.BalanceChange = &v
}

// GetCumulativeDeposits returns the CumulativeDeposits field value
func (o *DeprecatedPortfolioMeasurement) GetCumulativeDeposits() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CumulativeDeposits
}

// GetCumulativeDepositsOk returns a tuple with the CumulativeDeposits field value
// and a boolean to check if the value has been set.
func (o *DeprecatedPortfolioMeasurement) GetCumulativeDepositsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CumulativeDeposits, true
}

// SetCumulativeDeposits sets field value
func (o *DeprecatedPortfolioMeasurement) SetCumulativeDeposits(v int64) {
	o.CumulativeDeposits = v
}

// GetCumulativeNumberSettlements returns the CumulativeNumberSettlements field value
func (o *DeprecatedPortfolioMeasurement) GetCumulativeNumberSettlements() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CumulativeNumberSettlements
}

// GetCumulativeNumberSettlementsOk returns a tuple with the CumulativeNumberSettlements field value
// and a boolean to check if the value has been set.
func (o *DeprecatedPortfolioMeasurement) GetCumulativeNumberSettlementsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CumulativeNumberSettlements, true
}

// SetCumulativeNumberSettlements sets field value
func (o *DeprecatedPortfolioMeasurement) SetCumulativeNumberSettlements(v int64) {
	o.CumulativeNumberSettlements = v
}

// GetCumulativeWithdrawals returns the CumulativeWithdrawals field value
func (o *DeprecatedPortfolioMeasurement) GetCumulativeWithdrawals() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CumulativeWithdrawals
}

// GetCumulativeWithdrawalsOk returns a tuple with the CumulativeWithdrawals field value
// and a boolean to check if the value has been set.
func (o *DeprecatedPortfolioMeasurement) GetCumulativeWithdrawalsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CumulativeWithdrawals, true
}

// SetCumulativeWithdrawals sets field value
func (o *DeprecatedPortfolioMeasurement) SetCumulativeWithdrawals(v int64) {
	o.CumulativeWithdrawals = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *DeprecatedPortfolioMeasurement) GetReason() string {
	if o == nil || o.Reason == nil {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeprecatedPortfolioMeasurement) GetReasonOk() (*string, bool) {
	if o == nil || o.Reason == nil {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *DeprecatedPortfolioMeasurement) HasReason() bool {
	if o != nil && o.Reason != nil {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *DeprecatedPortfolioMeasurement) SetReason(v string) {
	o.Reason = &v
}

// GetTs returns the Ts field value
func (o *DeprecatedPortfolioMeasurement) GetTs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Ts
}

// GetTsOk returns a tuple with the Ts field value
// and a boolean to check if the value has been set.
func (o *DeprecatedPortfolioMeasurement) GetTsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ts, true
}

// SetTs sets field value
func (o *DeprecatedPortfolioMeasurement) SetTs(v int64) {
	o.Ts = v
}

// GetV returns the V field value
func (o *DeprecatedPortfolioMeasurement) GetV() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.V
}

// GetVOk returns a tuple with the V field value
// and a boolean to check if the value has been set.
func (o *DeprecatedPortfolioMeasurement) GetVOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.V, true
}

// SetV sets field value
func (o *DeprecatedPortfolioMeasurement) SetV(v int64) {
	o.V = v
}

func (o DeprecatedPortfolioMeasurement) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["a"] = o.A
	}
	if o.BalanceChange != nil {
		toSerialize["balance_change"] = o.BalanceChange
	}
	if true {
		toSerialize["cumulative_deposits"] = o.CumulativeDeposits
	}
	if true {
		toSerialize["cumulative_number_settlements"] = o.CumulativeNumberSettlements
	}
	if true {
		toSerialize["cumulative_withdrawals"] = o.CumulativeWithdrawals
	}
	if o.Reason != nil {
		toSerialize["reason"] = o.Reason
	}
	if true {
		toSerialize["ts"] = o.Ts
	}
	if true {
		toSerialize["v"] = o.V
	}
	return json.Marshal(toSerialize)
}

type NullableDeprecatedPortfolioMeasurement struct {
	value *DeprecatedPortfolioMeasurement
	isSet bool
}

func (v NullableDeprecatedPortfolioMeasurement) Get() *DeprecatedPortfolioMeasurement {
	return v.value
}

func (v *NullableDeprecatedPortfolioMeasurement) Set(val *DeprecatedPortfolioMeasurement) {
	v.value = val
	v.isSet = true
}

func (v NullableDeprecatedPortfolioMeasurement) IsSet() bool {
	return v.isSet
}

func (v *NullableDeprecatedPortfolioMeasurement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeprecatedPortfolioMeasurement(val *DeprecatedPortfolioMeasurement) *NullableDeprecatedPortfolioMeasurement {
	return &NullableDeprecatedPortfolioMeasurement{value: val, isSet: true}
}

func (v NullableDeprecatedPortfolioMeasurement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeprecatedPortfolioMeasurement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


