/*
Kalshi API.

This documentation describes Kalshi's REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kalshiAPI

import (
	"encoding/json"
)

// UserGetBalanceResponse struct for UserGetBalanceResponse
type UserGetBalanceResponse struct {
	Balance int64 `json:"balance"`
}

// NewUserGetBalanceResponse instantiates a new UserGetBalanceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserGetBalanceResponse(balance int64) *UserGetBalanceResponse {
	this := UserGetBalanceResponse{}
	this.Balance = balance
	return &this
}

// NewUserGetBalanceResponseWithDefaults instantiates a new UserGetBalanceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserGetBalanceResponseWithDefaults() *UserGetBalanceResponse {
	this := UserGetBalanceResponse{}
	return &this
}

// GetBalance returns the Balance field value
func (o *UserGetBalanceResponse) GetBalance() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value
// and a boolean to check if the value has been set.
func (o *UserGetBalanceResponse) GetBalanceOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Balance, true
}

// SetBalance sets field value
func (o *UserGetBalanceResponse) SetBalance(v int64) {
	o.Balance = v
}

func (o UserGetBalanceResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["balance"] = o.Balance
	}
	return json.Marshal(toSerialize)
}

type NullableUserGetBalanceResponse struct {
	value *UserGetBalanceResponse
	isSet bool
}

func (v NullableUserGetBalanceResponse) Get() *UserGetBalanceResponse {
	return v.value
}

func (v *NullableUserGetBalanceResponse) Set(val *UserGetBalanceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserGetBalanceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserGetBalanceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserGetBalanceResponse(val *UserGetBalanceResponse) *NullableUserGetBalanceResponse {
	return &NullableUserGetBalanceResponse{value: val, isSet: true}
}

func (v NullableUserGetBalanceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserGetBalanceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


